#!/bin/bash

# Rebase from the point at which this branch diverges from anything that's been published
git rebase $(git for-each-ref --format '%(refname)' refs/remotes/ | xargs git merge-base HEAD) "$@"
