#!/bin/bash -e

# Removes whitespace errors (as configued by core.whitespace) from both the working
# tree and the index.
# Goes to some lengths to avoid problems that could be caused by applying two mechanically
# altered patches in sequence.
to_work=`tempfile`
to_index=`tempfile`

# If there's no HEAD yet, use the empty tree
head=$(git rev-parse --verify --quiet HEAD || echo "4b825dc642cb6eb9a060e54bf8d69288fbee4904")

# take a diff from HEAD to the working tree.
git diff-index $head --full-index -p > $to_work

# take a diff from HEAD to the index.
git diff-index $head --cached --full-index -p > $to_index

# recreate the working tree without whitespace errors (throws away the index)
git reset $head --hard
git apply $to_work --whitespace=fix

# recreate the index without whitespace errors (preserves the working tree)
git reset $head --mixed
git apply $to_index --whitespace=fix --cached

rm $to_index $to_head
