#!/bin/bash

# Switches the order of the two most recent commits.
#
# You should only do this if the commits are independent (or you'll get a merge
# conflict). If you do get a merge conflict then `git rebase --abort` will save
# you.
#
# See also: git-pop

if [ "$1" = "--ed" ]
then
  ed -s $2 <<EOF
1m2
wq
EOF

else
  EDITOR="$0 --ed" git rebase -i HEAD~2
fi
