#!/bin/bash -e
#
# usage: git new-branch <branch-name>
#
# creates a new branch based on all your local commits since the last push
# (useful if you've just realised that you committed to master!)
: ${1:?No branch name specified}
if ! git rev-parse --verify "$1" >/dev/null 2>&1
then
    if git rev-parse --verify @{u} >/dev/null 2>&1
    then
        git reset --soft $(git merge-base HEAD @{u})
    else
        echo "no most recent push found"
        exit 1
    fi
    git checkout -b "$1" HEAD@{1}
fi
