#!/bin/bash
git branch --merged=master | grep -v '*' | grep -v master # | xargs -l1 git branch -d
#git branch -a --merged=origin/master | grep -v 'origin/master' | grep -v 'origin/HEAD' | grep -v '*' # | sed 's,remotes/origin/,,' #| xargs git push origin --delete
