#!/bin/bash

if [ $# = 0 ]
then
    branches="$(git remote -v | sed 's/\t.*/\/master/' | tr '\n' ' ')"
else
    branches="$@"
fi

git plog HEAD $branches --not $(git show-branch --merge-base HEAD $branches  | sed 's/ /^@ /g')^@
