#!/bin/bash -e

# Removes whitespace errors (as configued by core.whitespace) from both the working
# tree and the index.
# Goes to some lengths to avoid problems that could be caused by applying two mechanically
# altered patches in sequence.
to_work=`mktemp -t git-nows.XXX`
to_index=`mktemp -t git-nows.XXX`

# If there's no HEAD yet, use the empty tree
head=$(git rev-parse --verify --quiet HEAD || echo "4b825dc642cb6eb9a060e54bf8d69288fbee4904")

# The base from which to remove all whitespace changes
from=$(git rev-parse --verify --quiet ${1:-$head})

# take a diff from HEAD to the working tree.
git diff-index $from --full-index -p > $to_work

# take a diff from $from to the index.
git diff-index $from --cached --full-index -p > $to_index

# recreate the working tree without whitespace errors (throws away the index)
git reset $from --hard
[ -s $to_work ] && git apply $to_work --whitespace=fix

# recreate the index without whitespace errors (preserves the working tree)
git reset $from --mixed
[ -s $to_index ] && git apply $to_index --whitespace=fix --cached

# reset head
git reset $head --soft

rm $to_index $to_head
